version: 0.2

env:
secrets-manager:
  AWS_ACCOUNT_ID: idanpersi-skills-cve-etl-accountID:AWS_ACCOUNT_ID

phases:
  install:
    runtime-versions:
      golang: 1.12
  pre_build:
    commands:
      - apt-get install wget apt-transport-https gnupg
      - wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | apt-key add -
      - echo deb https://aquasecurity.github.io/trivy-repo/deb bionic main | tee -a /etc/apt/sources.list.d/trivy.list
      - apt-get update
      - apt-get install -y trivy
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
      - IMAGE_AND_TAG=$REPOSITORY_URI:$CODEBUILD_BUILD_NUMBER
  build:
    commands:
      - docker build -t $IMAGE_AND_TAG .
  post_build:
    commands:
      - trivy --no-progress --exit-code 1 --severity HIGH,CRITICAL $IMAGE_AND_TAG
      - docker push $IMAGE_AND_TAG
