services:
  app:
    build: .
    image: cve_importer_app:latest
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: python -m src.main
    volumes:
      - .:/app  

  api:
    build: .
    image: cve_importer_app:latest
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
    command: uvicorn src.api.api:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    
  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: