[pytest]
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .


addopts = 
    -v
    --tb=short
    --strict-markers
    --color=yes
    -ra
    --cov-report=html
    --cov-report=term-missing

[coverage:run]
omit = 
    test_*.py
    */tests/*
    */__pycache__/*
    */venv/*
    */virtualenv/*

[coverage:report]
precision = 2
show_missing = True
skip_covered = False